name: Update Daily PM2.5 Data from Thailand

# Permissions are needed for automatic updates committing
permissions:
  contents: write

# The 'on' section specifies when the workflow runs
on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: "0 8 * * *"  # Runs daily at 8 AM UTC

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run updater script
      run: python updater.py

    - name: Commit and push changes
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add pm25_data_*.json  # Add updated JSON files
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
